---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"
    full_locale: "{{ lookup('env', 'LANG') }}"

### Read in the variables from the vault file and do not log the values!
- name: Include the variables from the vault file
  include_vars:
    file: vault.yml
  no_log: true

### Determine if the system has a wireless adapter.
- name: Check for wireless adapter
  command: ifconfig wlan0
  register: wireless
  ignore_errors: true

### Render the wifi template only for systems with wireless adapters and wifi variables.
- name: Render a new wifi template
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: '0600'
    backup: yes
  when: ( wireless.rc == 0 ) and ( wifi_ssid is defined ) and ( wifi_password is defined )

### Copy the local ssh key to the managed host.
- name: Copy the public ssh key from the Ansible host to the managed host
  authorized_key:
    user: pi
    state: present
    key: "{{ item }}"
  with_file:
    - "~/.ssh/id_rsa.pub"

### Set the timezone.
- name: Change the timezone
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone'
    force: yes

### Set the keyboard layout.
- name: Change the keyboard layout
  replace:
    path: /etc/default/keyboard
    regexp: 'XKBLAYOUT=.+'
    replace: 'XKBLAYOUT="{{ country }}"'
    backup: yes

### Render a locale file with the LANG env variable from local host so the next task can read it.
- name: Render the locale file
  template:
    src: locales.j2
    dest: /tmp/locales

### Set selections, remove generated, reconfigure and update locale.
- name: Change the locale
  command: "{{ item }}"
  with_items:
    - debconf-set-selections /tmp/locales
    - rm /etc/locale.gen
    - dpkg-reconfigure -f noninteractive locales
    - update-locale LANG='{{ full_locale }}'
    - rm /tmp/locales

### Change the password to new_pi_password from the vault file.
- name: Change the password to something else
  user:
    name: pi
    password: "{{ new_pi_password | password_hash('sha512') }}"
  when: new_pi_password is defined

### Update the package manager.
- name: Update package manager cache
  apt:
    update_cache: yes

### Update the packages to the latest version.
- name: Upgrade packages to the latest version
  apt:
    upgrade: yes

### Remove the unnecessary packages.
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

### Remove the downloaded packages.
- name: Remove useless packages from the cache
  apt:
    autoclean: yes

### Update the Raspberry Pi firmware, this may require a reboot.
- name: Update the Raspberry Pi firmware
  command: rpi-update
  ignore_errors: true

### Reboot the the managed host.
- name: Restart the system
  shell: sleep 2 && shutdown -r now "Ansible requested system reboot"
  async: 1
  poll: 0
  ignore_errors: true

### Wait for the managed host to return.
- name: Wait for system to boot
  become: false
  vars:
    ansible_connection: local
  local_action: wait_for
  args:
    host: "{{ real_ansible_host }}"
    port: 22
    state: started
    delay: 15
    timeout: 300
